### ISSUE TITLE
[ERC Registry] Phase 2: Utilize contract call mirror node API for enhanced accuracy and to retrieve token details.

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#1059]
### Problem  
The ERC indexing tool can now detect ERC contracts and categorize them into ERC-20 and ERC-721. However, the categorized contracts only include the contract ID and EVM address, lacking other essential information such as name, symbol, and decimals.

### Solution  
Implement a new mechanism to make calls to the mirror node to retrieve the necessary information.

**Comment by acuarica** [comment]
As an alternative we could use https://github.com/cdump/evmole (similar to sevm) to extract function selectors. The good thing about evmole is that it seems it allows us to detect the slot values read by a method statically. See for example https://evmole.xyz/#0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/eth

![Image](https://github.com/user-attachments/assets/904e1567-40cd-42cd-a418-e0fc720eab74)

This way instead of making one `eth_call` for each value we want to retrieve, we can get all desired slots in one go using https://testnet.mirrornode.hedera.com/api/v1/docs/#/contracts/getContractState.

**Comment by acuarica** [comment]
Another alternative could be to deploy a wrapper contract to get the ERC20 metadata in one go, for example

```solidity
contract ERC20Metadata {
    struct Metadata {
        string name;
        string symbol;
        uint8 decimals;
        uint256 totalSupply;
    }

    function getTokenMetadata(address erc20Address) external view returns (Metadata memory metadata) {
        metadata.name = IERC20(erc20Address).name();
        metadata.symbol = IERC20(erc20Address).symbol();
        metadata.decimals = IERC20(erc20Address).decimals();
        metadata.totalSupply = IERC20(erc20Address).totalSupply();
    }
}
```

this way, we get the real information from the network with only making one request per address.
